### ISSUE TITLE
Any restriction to implement Poseidon for more than 5 inputs?

### ISSUE THREAD

**Issue by AndriianChestnykh** [vimwitch/poseidon-solidity#2]
Hi,

Thank you for the Poseidon hash implementation, which is quite gas efficient.
However, currently we need EVM-based Poseidon with 16 inputs in our tech stack and considering if it is worth to implement it. So I wonder if there are some fundamental limitations, which prevented you from implementing the hash for more than 5 inputs or that is just because luck of demand from your/community side?

**Comment by vimwitch** [comment]
Yes there is a limitation based on the maximum stack depth of the evm. To support more than 5 inputs the variables need to be stored and retrieved from heap memory. In [this commit](https://github.com/vimwitch/poseidon-solidity/tree/dce1d8fe8f56b4dcbdbdf205cb4c9651f9bcbbdb) i supported up to 8 input poseidon using the memory approach, but it's significantly more expensive at runtime and the contract size is much larger.

If you want to hash 16 inputs it will maybe be cheaper to perform 5 hashes using 4 inputs each. e.g. form a 4-ary merkle tree of depth 2:

```js
hash16(input: []) {
  return hash4([
    hash4(input[0..4]), hash4(input[4..8]), hash4(input[8..12]), hash4(input[12..16])
  ])
}
````

**Comment by AndriianChestnykh** [comment]
Wow! That's really nice you've implemented it in that way as well!!
Yes, tis id possible to have a workaround by merkle tree or some kind of a sponge hashing. However in our specific case we have restriction integration-wise. Some components of our system use off-chain Poseidon hashing up to 16 inputs. We can't always influence how exactly the hash is done.
Anyway, thanks for the prompt and provided example. It may be useful in the future.
